compatible: nabucasa,esphome-switch-gpio
description: |
  The switch domain includes all platforms that should show up like a switch and can only be turned ON or OFF
properties:
  id:
    type: string
    required: false
  device_name:
    type: string
    required: false
  inverted:
    type: boolean
    required: false
  internal:
    type: boolean
    required: false
  restore_mode:
    type: string
    required: false
    enum:
      - "RESTORE_DEFAULT_OFF"
      - "RESTORE_DEFAULT_ON"
      - "RESTORE_INVERTED_DEFAULT_OFF"
      - "RESTORE_INVERTED_DEFAULT_ON"
      - "ALWAYS_OFF"
      - "ALWAYS_ON"
      - "DISABLED"
  on_turn_on:
    type: string
    required: false
  on_turn_off:
    type: string
    required: false
  gpios:
    type: phandle-array
    required: true
