compatible: nabucasa,esphome-switch-hbridge
description: |
  The hbridge switch platform allows you to drive an h-bridge controlled latching relay.
properties:
  id:
    type: string
    required: false
  device_name:
    type: string
    required: false
  inverted:
    type: boolean
    required: false
  internal:
    type: boolean
    required: false
  restore_mode:
    type: string
    required: false
    enum:
      - "RESTORE_DEFAULT_OFF"
      - "RESTORE_DEFAULT_ON"
      - "RESTORE_INVERTED_DEFAULT_OFF"
      - "RESTORE_INVERTED_DEFAULT_ON"
      - "ALWAYS_OFF"
      - "ALWAYS_ON"
      - "DISABLED"
  on_turn_on:
    type: string
    required: false
  on_turn_off:
    type: string
    required: false
  on-gpios:
    type: phandle-array
    required: true
  off-gpios:
    type: phandle-array
    required: true
  pulse_length:
    type: int
    required: false
  wait_time:
    type: int
    required: false
